# Sample Config File for star_yuuki_bot
# Please replace setting options from `libs/config.py`

Yuuki:
  SecurityService: True
  Default_Language: en

LINE:
  Server:
    Host: https://example.com
    Command_Path: /example_path
    LongPoll_path: /example_path

  Account:
    X-Line-Application: LINE_Application_Identification
    X-Line-Access: LINE_Application_AccessKey
    User-Agent: LINE_Application_User-Agent
